spring.profiles.active=prod

# Configuração de Banco de Dados para Produção
spring.datasource.url=jdbc:postgresql://localhost:5432/washing_db
spring.datasource.username=postgres
spring.datasource.password=postgres

# JPA / Hibernate - DESATIVADO
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

# Pool de Conexões (Hikari)
spring.datasource.hikari.maximum-pool-size=10