spring.datasource.url=jdbc:postgresql://localhost:5432/washing_db
spring.datasource.username=postgres
spring.datasource.password=Lyo0712!

# Esta linha é a mais importante para criar a tabela automaticamente
spring.jpa.hibernate.ddl-auto=update

# Ajuda o Spring a falar a "língua" certa do Postgres
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect